services:
  # --- Service to run the Task-CL Experiment ---
  cl_case2-experiment:
    build:
      context: ./cl_case2
    command: python case2_sim.py
    volumes:
      - ./cl_case2/cyber:/app/cyber
      - ./cl_case2/results:/app/results
    environment:
      - MPLBACKEND=Agg

  # --- Service to run the Task-Domain-CL Experiment ---
  cl_case1-experiment:
    build:
      context: ./cl_case1
    command: python case1_sim.py
    volumes:
      - ./cl_case1/cyber:/app/cyber
      - ./cl_case1/results:/app/results
    environment:
      - MPLBACKEND=Agg

  # --- Service to run the Online (Correct Scaling) Experiment ---
  online-experiment:
    build:
      context: ./online
    command: python online.py
    volumes:
      - ./online/cyber:/app/cyber
      - ./online/results:/app/results
    environment:
      - MPLBACKEND=Agg

  batch-learning-experiment:
    build:
      context: ./batch
    command: python batch_sim.py
    volumes:
      - ./batch/cyber:/app/cyber
      - ./batch/results:/app/results
    environment:
      - MPLBACKEND=Agg